[build]
command = "npm run build"
publish = "out"

[[redirects]]
from = "/product"
to = "/oplossingen"
status = 301
force = true

[[redirects]]
from = "/product/*"
to = "/oplossingen"
status = 301
force = true
